always_exclude:
  exact_patterns:
  - _hour
  - ad_line
  - adx_14
  - adx_x_vol
  - atr_14
  - atr_x_vol
  - bb_lower_20
  - bb_upper_20
  - bb_width_20
  - cci_30
  - close
  - cmf
  - dollar_volume
  - gk_vol_5
  - hull_ma_20
  - hull_ma_5
  - kama_20
  - low
  - low_loc_1d
  - macd_hist
  - macd_signal
  - macd_x_ret
  - macd_x_vol
  - mfi_14
  - momentum_10
  - n_trades
  - negative_volume_index
  - obv
  - obv_ema
  - parkinson_vol_5
  - price_volume_trend
  - realized_vol_5
  - ret2_15m
  - ret_1m
  - ret_30m
  - ret_60m
  - ret_oc
  - ret_ord_30m
  - ret_ord_60m
  - ret_zscore_10m
  - ret_zscore_15m
  - ret_zscore_30m
  - ret_zscore_5m
  - ret_zscore_60m
  - rs_vol_5
  - rsi_30
  - rsi_5
  - rsi_7
  - rsi_x_vol
  - stoch_d_5
  - stoch_k_5
  - stoch_x_vol
  - trade_size_vol
  - turnover_20
  - turnover_5
  - vol_15m
  - vol_30m
  - vol_5m
  - vol_60m
  - vol_over_vol_15m
  - vol_over_vol_5m
  - vol_over_vol_60m
  - vol_persistence
  - vol_x_ret_15m
  - vol_x_ret_60m
  - volume
  - volume_ema_20
  - volume_ema_5
  - volume_momentum_5d
  - volume_price_trend
  - volume_roc_10
  - volume_roc_20
  - volume_roc_5
  - volume_sma_5
  - vwap_dev
  - vwap_dev_high
  - vwap_dev_low
  - vwma_20
  keyword_patterns: []
  prefix_patterns: []
  regex_patterns: []
